on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Testing Github action"
        run: pwd

      - name: "files before"
        run: ls

      - uses: actions/checkout@v3

      - name: "files after"
        run: ls
